# Generated by Django 5.0.6 on 2024-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorehouseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashless_payment', models.BooleanField(default=False, verbose_name='Безналичный расчет')),
                ('sender_name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Номер телефона отправителя')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='ФИО получателя')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='Номер телефона получателя')),
                ('places_count', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплачено')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Приложить фото')),
            ],
        ),
    ]
